### ISSUE TITLE
map.de -> wrong parse result

### ISSUE THREAD

**Issue by semen-cliqz** [mjpearson/node-tldtools#7]
for "map.de" returns null domain, forced to use a workaround:

var base = domain == "map.de"?"map":tldtools.extract(punycode.toUnicode(domain)).domain

probably, could be connected to .map property of JS object...

**Comment by mjpearson** [comment]
Hi, the underlying url.parse() method won't return a hostname if it doesn't have a URI preamble, added in https://github.com/mjpearson/node-tldtools/commit/4dc66a33bd745498b58e3d2190b3066fe2e3b299#diff-168726dbe96b3ce427e7fedce31bb0bc

let me know if that still doesn't work

-michael
